apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrends
    tag: latest
  name: techtrends
  namespace: {{.Values.namespace.name}}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: techtrends
      tag: latest
  template:
    metadata:
      labels:
        app: techtrends
        tag: latest
    spec:
      containers:
      - image: {{.Values.image.repository}}:{{.Values.image.tag}}
        imagePullPolicy: {{.Values.imagePullPolicy}}
        name: techtrends
        ports:
        - containerPort: {{.Values.containers.port}}
        resources:
{{ toYaml .Values.resources | indent 12 }}
        livenessProbe:
{{ toYaml .Values.livenessProbe | indent 12 }}
        readinessProbe:
{{ toYaml .Values.readinessProbe | indent 12 }}
