name: TechTrends - Package with Docker
## The workflow will be executed on a `push` event,
## or when a new commit will be pushed to the repository
on:
  push:
    branches:
      - 'main'
jobs:
  docker:
    ## Operating system the workflow will run on.
    runs-on: ubuntu-latest
    ## Sequence of steps to execute 
    steps:
      ## Use the public `checkout` actoin  in version v2  
      ## to checkout the existing code in the repository
      - 
        name: checkout
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: techtrends:latest